import type { CaseBundle, ProofCardPayload } from "./api";

export const DEMO_CASES: Record<string, CaseBundle> = {
  "CASE-1042": {
    case: {
      id: "CASE-1042",
      prisoner_id: "P-1042",
      fir_number: "FIR 221/2024",
      court: "Sessions Court, Chennai",
      sections: ["IPC 379", "IPC 411"],
      custody_start: "2024-01-15",
      maximum_sentence_years: 3,
      first_time_offender: true,
      multiple_pending_cases: false,
      punishable_by_death_or_life: false,
      next_hearing: "2026-08-28",
      documents: 6,
      is_uploaded: false,
    },
    prisoner: {
      id: "P-1042",
      name: "Aarav Kumar",
      prison_number: "TNP-1042",
      age: 29,
      gender: "Male",
      prison_name: "Central Prison, Puzhal",
      district: "Chennai",
      state: "Tamil Nadu",
      risk: "Low",
    },
    decision: {
      case_id: "CASE-1042",
      status: "ELIGIBLE",
      outcome: "ELIGIBLE_FOR_SECTION_479_RELEASE",
      eligible: true,
      detention_days: 412,
      qualifying_detention_days: 412,
      threshold_days: 365,
      days_remaining: 0,
      progress_percent: 112,
      excluded_delay_days: 0,
      rule_version: "2024.1",
      legal_basis: "Section 479(1) First Proviso BNSS",
      reasons: [
        "First-time offender has completed 412 days in custody, exceeding the 1/3 statutory threshold (365 days) for maximum sentence of 3 years.",
      ],
      exclusions: [],
      flags: [],
      trace: [
        {
          step: "Exclusion Check: Heinous / Capital / Life Offence",
          result: "PASS",
          detail: "Charges IPC 379/411 carry max sentence 3 years; not punishable by death or life imprisonment.",
        },
        {
          step: "Exclusion Check: Multiple Pending Cases",
          result: "PASS",
          detail: "Verified single pending case record across ICJS / e-Courts database.",
        },
        {
          step: "Classification: First-Time Offender Proviso",
          result: "APPLIED",
          detail: "First-time offender verified under Section 479 First Proviso (1/3 fraction applies instead of 1/2).",
        },
        {
          step: "Threshold Calculation (1/3 of Max Sentence)",
          result: "COMPUTED",
          detail: "1/3 × 3 years (1095 days) = 365 days statutory threshold.",
        },
        {
          step: "Accused-Caused Delay Deduction",
          result: "ZERO_DEDUCTION",
          detail: "0 days accused-caused delay recorded in court order sheets. Qualifying custody = 412 days.",
        },
        {
          step: "Statutory Eligibility Determination",
          result: "ELIGIBLE",
          detail: "Qualifying custody (412 days) >= Threshold (365 days). Overdue for Section 479 release by 47 days.",
        },
      ],
      requires_human_review: false,
      generated_at: "2026-08-19T10:00:00Z",
    },
    workflow: {
      case_id: "CASE-1042",
      levels: [
        {
          level: 1,
          role: "Legal Aid Defense Counsel",
          status: "APPROVED",
          actor: "Adv. K. Sundaram (DLSA Chennai)",
          note: "Verified FIR 221/2024 and remand order. 1/3 threshold met.",
          at: "2026-08-18T14:30:00Z",
        },
        {
          level: 2,
          role: "DLSA Secretary / Judicial Magistrate",
          status: "PENDING",
          actor: null,
          note: null,
          at: null,
        },
      ],
      current_level: 2,
      final_decision: "PENDING",
      next_action: "Awaiting DLSA Secretary / Judicial Magistrate final Section 479 bond order",
    },
    perception_info: {
      ocr_provider: "EasyOCR Engine (PyTorch)",
      llm_provider: "Groq Llama-3-70B (Cloud / Fallback: Ollama Llama-3 Edge)",
      extraction_confidence: 0.98,
      raw_text_preview: "IN THE COURT OF SESSIONS JUDGE, CHENNAI · SC/412/2024 · FIR NO: 221/2024 · ACCUSED: AARAV KUMAR · CUSTODY REMAND: 15-01-2024",
    },
    document_lines: [
      "IN THE COURT OF PRINCIPAL SESSIONS JUDGE, CHENNAI",
      "SESSIONS CASE NO: SC/412/2024 · ARISING FROM CRIME NO: 221/2024",
      "POLICE STATION: CRIME BRANCH (CENTRAL), CHENNAI DISTRICT",
      "STATE OF TAMIL NADU  --- VERSUS ---  AARAV KUMAR S/O R. KUMAR",
      "UNDER SECTIONS: 379 IPC (THEFT), 411 IPC (RECEIVING STOLEN PROPERTY)",
      "DATE OF INITIAL REMAND INTO JUDICIAL CUSTODY: 15-01-2024",
      "MAXIMUM PRESCRIBED STATUTORY SENTENCE: 3 YEARS RIGOROUS IMPRISONMENT",
      "CONVICTION RECORD CHECK: NO PRIOR CONVICTIONS ON ICJS (FIRST-TIME OFFENDER)",
      "MULTIPLE PROCEEDINGS: ZERO OTHER PENDING INVESTIGATIONS OR SESSIONS CASES",
      "ORDER OF ADJOURNMENTS: ALL PRE-TRIAL HEARINGS PROCEEDED UNDER COURT SCHEDULE",
      "ACCUSED-ATTRIBUTABLE DELAYS RECORDED: NIL (0 DAYS DEDUCTION)",
      "TOTAL CONTINUOUS CUSTODY SERVED (AS OF 19-08-2026): 412 DAYS",
      "STATUTORY APPLICABILITY: SECTION 479(1) FIRST PROVISO BNSS (1/3 THRESHOLD = 365 DAYS)",
      "DISPOSITION RECOMMENDATION: ELIGIBLE FOR MANDATORY BAIL REVIEW UNDER BNSS S.479",
    ],
    conflicts: {
      has_conflict: false,
      status: "RECONCILED",
      adjudication_rule: "Truth Discovery Protocol: Court Order (1.0) = e-Prisons (0.95) = Police FIR (0.85).",
      hierarchy: [
        { source: "Court Remand Order", weight: 1.0, rank: "1st" },
        { source: "e-Prisons Central Register", weight: 0.95, rank: "2nd" },
        { source: "Police FIR / CCTNS", weight: 0.85, rank: "3rd" },
        { source: "OCR Perception Engine", weight: 0.75, rank: "4th" },
      ],
      columns: [
        {
          source_name: "e-Prisons Register",
          authority: "Central Prison, Puzhal",
          recorded_value: "Admission Date: 15-01-2024",
          detention_days: 412,
          reliability_score: 0.95,
          status: "PRIMARY",
          notes: "Biometric intake log records 412 continuous days without release on bail or furlough.",
        },
        {
          source_name: "Court Remand Sheet",
          authority: "Principal Sessions Court, Chennai",
          recorded_value: "Remand Date: 15-01-2024",
          detention_days: 412,
          reliability_score: 1.0,
          status: "PRIMARY",
          notes: "Judicial order sheets corroborate 412 days total remand with 0 days defense delay.",
        },
        {
          source_name: "Police FIR / CCTNS",
          authority: "Crime Branch, Chennai",
          recorded_value: "Arrest Date: 14-01-2024",
          detention_days: 412,
          reliability_score: 0.85,
          status: "CORROBORATING",
          notes: "Charge sheet filed on time; zero companion pending FIRs registered in Tamil Nadu.",
        },
      ],
      resolution_action: "All 3 repositories match in 100% agreement. No judicial conflict resolution needed.",
    },
  },
  "CASE-5099": {
    case: {
      id: "CASE-5099",
      prisoner_id: "P-5099",
      fir_number: "FIR 71/2022",
      court: "Sessions Court, Kolkata",
      sections: ["IPC 302", "IPC 34"],
      custody_start: "2022-11-22",
      maximum_sentence_years: 10,
      first_time_offender: false,
      multiple_pending_cases: true,
      punishable_by_death_or_life: true,
      next_hearing: "2026-08-29",
      documents: 11,
      is_uploaded: false,
    },
    prisoner: {
      id: "P-5099",
      name: "Rohit Das",
      prison_number: "WB-5099",
      age: 52,
      gender: "Male",
      prison_name: "Presidency Correctional Home",
      district: "Kolkata",
      state: "West Bengal",
      risk: "High",
    },
    decision: {
      case_id: "CASE-5099",
      status: "INELIGIBLE",
      outcome: "STATUTORY_EXCLUSION_LIFE_DEATH",
      eligible: false,
      detention_days: 640,
      qualifying_detention_days: 640,
      threshold_days: null,
      days_remaining: null,
      progress_percent: 0,
      excluded_delay_days: 0,
      rule_version: "2024.1",
      legal_basis: "Section 479(1) Exclusion Bar BNSS",
      reasons: [
        "Statutory Bar: Undertrial is charged with IPC 302 punishable by death or life imprisonment, which is explicitly disqualified from Section 479 BNSS relief.",
      ],
      exclusions: ["PUNISHABLE_BY_DEATH_OR_LIFE", "MULTIPLE_PENDING_CASES"],
      flags: ["STATUTORY_DISQUALIFICATION_TRIGGERED"],
      trace: [
        {
          step: "Exclusion Check: Heinous / Capital / Life Offence",
          result: "FAIL",
          detail: "Charge under IPC 302 specifies punishment of death or life imprisonment. Section 479(1) BNSS categorically bars release.",
        },
        {
          step: "Exclusion Check: Multiple Pending Cases",
          result: "FAIL",
          detail: "Multiple pending sessions trials detected in e-Courts CCTNS record.",
        },
        {
          step: "Threshold Calculation",
          result: "BLOCKED",
          detail: "Computation halted at Exclusion Gate. Zero-bail recommendation enforced by statutory mandate.",
        },
      ],
      requires_human_review: true,
      generated_at: "2026-08-19T10:00:00Z",
    },
    workflow: {
      case_id: "CASE-5099",
      levels: [
        {
          level: 1,
          role: "Legal Aid Defense Counsel",
          status: "REJECTED",
          actor: "Adv. S. Chatterjee (DLSA Kolkata)",
          note: "Ineligible due to Section 302 IPC life imprisonment bar.",
          at: "2026-08-17T11:15:00Z",
        },
        {
          level: 2,
          role: "DLSA Secretary / Judicial Magistrate",
          status: "LOCKED",
          actor: null,
          note: null,
          at: null,
        },
      ],
      current_level: 1,
      final_decision: "REJECTED",
      next_action: "Case closed as Ineligible under BNSS Section 479(1) statutory bar.",
    },
    perception_info: {
      ocr_provider: "EasyOCR Engine (PyTorch)",
      llm_provider: "Groq Llama-3-70B (Cloud / Fallback: Ollama Llama-3 Edge)",
      extraction_confidence: 0.99,
      raw_text_preview: "HIGH COURT OF CALCUTTA / SESSIONS COURT KOLKATA · SC/71/2022 · SECTIONS: 302 IPC, 34 IPC · MULTIPLE CASES FOUND IN CCTNS",
    },
    document_lines: [
      "IN THE SESSIONS COURT AT KOLKATA, WEST BENGAL",
      "SESSIONS TRIAL CASE NO: ST/71/2022 · ARRESTING PS: TALTALA",
      "STATE OF WEST BENGAL  --- VERSUS ---  ROHIT DAS S/O LATE B. DAS",
      "CHARGES FRAMED UNDER: SECTION 302 IPC (MURDER) READ WITH SECTION 34 IPC",
      "STATUTORY PENALTY: PUNISHABLE WITH DEATH OR IMPRISONMENT FOR LIFE",
      "INTER-STATE CRIMINAL RECORD: 2 OTHER SESSIONS TRIALS PENDING IN ALIPORE COURT",
      "DATE OF COMMENCEMENT OF DETENTION: 22-11-2022",
      "TOTAL CUSTODY SERVED TO DATE: 640 DAYS IN PRESIDENCY CORRECTIONAL HOME",
      "STATUTORY EXCLUSION ANALYSIS UNDER SECTION 479(1) BNSS:",
      "1. CAPITAL / LIFE IMPRISONMENT CLAUSE: EXCLUDED UNDER SECTION 479(1)",
      "2. MULTIPLE PENDING PROCEEDINGS CLAUSE: EXCLUDED UNDER SECTION 479(2)",
      "FINAL DETERMINATION: ZERO-BAIL MANDATORY DISQUALIFICATION APPLIED",
    ],
    conflicts: {
      has_conflict: false,
      status: "RECONCILED",
      adjudication_rule: "Statutory Exclusion Hierarchy: Section 302 IPC bar is confirmed identically across all records.",
      hierarchy: [
        { source: "Charge Sheet (Sessions Court)", weight: 1.0, rank: "1st" },
        { source: "e-Prisons Intake Register", weight: 0.95, rank: "2nd" },
        { source: "CCTNS Inter-State Portal", weight: 0.85, rank: "3rd" },
        { source: "OCR Perception Engine", weight: 0.75, rank: "4th" },
      ],
      columns: [
        {
          source_name: "e-Prisons Register",
          authority: "Presidency Correctional Home",
          recorded_value: "Charge: IPC Section 302 (Murder)",
          detention_days: 640,
          reliability_score: 0.95,
          status: "PRIMARY",
          notes: "Prison warrant records heinous offence category. Disqualification verified on admission.",
        },
        {
          source_name: "Court Charge Sheet",
          authority: "Sessions Court, Kolkata",
          recorded_value: "Framed: IPC 302/34 (Life/Death)",
          detention_days: 640,
          reliability_score: 1.0,
          status: "PRIMARY",
          notes: "Court charges confirm life imprisonment penalty. Statutory bar under S.479(1) applies.",
        },
        {
          source_name: "Police FIR / CCTNS",
          authority: "Taltala Police Station",
          recorded_value: "2 Pending Trials in Alipore Court",
          detention_days: 640,
          reliability_score: 0.85,
          status: "CORROBORATING",
          notes: "CCTNS database confirms separate pending murder trial in neighboring district.",
        },
      ],
      resolution_action: "Disqualification unanimous across all databases. Zero-bail rule confirmed without ambiguity.",
    },
  },
  "CASE-3156": {
    case: {
      id: "CASE-3156",
      prisoner_id: "P-3156",
      fir_number: "FIR 19/2025",
      court: "Sessions Court, Pune",
      sections: ["IPC 307"],
      custody_start: "2023-08-10",
      maximum_sentence_years: 10,
      first_time_offender: false,
      multiple_pending_cases: false,
      punishable_by_death_or_life: false,
      next_hearing: "2026-08-25",
      documents: 4,
      is_uploaded: false,
    },
    prisoner: {
      id: "P-3156",
      name: "Imran Khan",
      prison_number: "MH-3156",
      age: 41,
      gender: "Male",
      prison_name: "Yerwada Central Prison",
      district: "Pune",
      state: "Maharashtra",
      risk: "Medium",
    },
    decision: {
      case_id: "CASE-3156",
      status: "ELIGIBLE_FLAGGED",
      outcome: "DISPUTED_ACCUSED_DELAY_REQUIRES_MAGISTRATE_REVIEW",
      eligible: true,
      detention_days: 950,
      qualifying_detention_days: 770,
      threshold_days: 1825,
      days_remaining: 1055,
      progress_percent: 42,
      excluded_delay_days: 180,
      rule_version: "2024.1",
      legal_basis: "Section 479(1) BNSS & Article 21 Safeguard",
      reasons: [
        "Source conflict between Prison Register (950 days) and Court Remand Log (180 days defense-caused adjournments). Excluded delay contested by legal aid counsel; flagged for judicial inquiry.",
      ],
      exclusions: [],
      flags: ["ACCUSED_DELAY_DISPUTE", "ARTICLE_21_HEARING_REQUIRED", "SOURCE_RECORD_MISMATCH"],
      trace: [
        {
          step: "Exclusion Check: Heinous / Capital / Life Offence",
          result: "PASS",
          detail: "IPC 307 maximum punishment is 10 years imprisonment; not death/life.",
        },
        {
          step: "Exclusion Check: Multiple Pending Cases",
          result: "PASS",
          detail: "Single pending trial verified in Pune District.",
        },
        {
          step: "Classification: General Undertrial",
          result: "APPLIED",
          detail: "Prior conviction on record; Section 479(1) standard 1/2 fraction applies (1825 days threshold).",
        },
        {
          step: "Accused-Caused Delay Deduction",
          result: "TRIGGER",
          detail: "Prosecution claims 180 days adjournment delay by defense under S.479(2). Defense disputes attribution.",
        },
        {
          step: "Truth Reconciliation & Flagging",
          result: "FLAGGED",
          detail: "Fails safe to human judicial determination. Case routed for Under Trial Review Committee hearing.",
        },
      ],
      requires_human_review: true,
      generated_at: "2026-08-19T10:00:00Z",
    },
    workflow: {
      case_id: "CASE-3156",
      levels: [
        {
          level: 1,
          role: "Legal Aid Defense Counsel",
          status: "APPROVED",
          actor: "Adv. P. Deshmukh (DLSA Pune)",
          note: "Flagged 180-day delay attribution as court delay rather than accused delay.",
          at: "2026-08-18T09:45:00Z",
        },
        {
          level: 2,
          role: "DLSA Secretary / Judicial Magistrate",
          status: "PENDING",
          actor: null,
          note: null,
          at: null,
        },
      ],
      current_level: 2,
      final_decision: "PENDING",
      next_action: "Judicial Magistrate determination on contested 180-day accused delay period.",
    },
    perception_info: {
      ocr_provider: "EasyOCR Engine (PyTorch)",
      llm_provider: "Groq Llama-3-70B (Cloud / Fallback: Ollama Llama-3 Edge)",
      extraction_confidence: 0.88,
      raw_text_preview: "SESSIONS COURT PUNE · CRIME NO: 19/2025 · PS SHIVAJINAGAR · ACCUSED: IMRAN KHAN · CONFLICT: 180 DAYS ADJOURNMENT ATTRIBUTION DISPUTED",
    },
    document_lines: [
      "IN THE COURT OF SESSIONS JUDGE AT PUNE, MAHARASHTRA",
      "SESSIONS CASE NO: 19/2025 · POLICE STATION: SHIVAJINAGAR",
      "STATE OF MAHARASHTRA  --- VERSUS ---  IMRAN KHAN",
      "CHARGES UNDER: SECTION 307 IPC (ATTEMPT TO MURDER) · MAX SENTENCE: 10 YEARS",
      "DATE OF PRISON ADMISSION (YERWADA PRISON): 10-08-2023 (950 DAYS IN CUSTODY)",
      "PROSECUTION MEMO: CLAIMS 180 DAYS DEFENSE ADJOURNMENT DELAY UNDER S.479(2)",
      "DLSA DEFENSE OBJECTION: 180 DAYS CAUSED BY PROSECUTION WITNESS ABSENCE",
      "QUALIFYING DETENTION COMPUTATION: 950 DAYS RAW - 180 DAYS CONTESTED = 770 DAYS",
      "STATUTORY THRESHOLD: 1/2 OF 10 YEARS = 5 YEARS (1825 DAYS)",
      "SOURCE CONFLICT DETECTED: PRISON REGISTER (950 DAYS) VS PROSECUTION DEDUCTION (770 DAYS)",
      "ARTICLE 21 STATUTORY SAFEGUARD: DEDUCTION CONTESTED; ESCALATED FOR MAGISTRATE HEARING",
    ],
    conflicts: {
      has_conflict: true,
      status: "CONFLICT_FLAGGED",
      adjudication_rule: "Section 479(2) BNSS & Article 21: Contested accused delay cannot be deducted without summary judicial inquiry.",
      hierarchy: [
        { source: "Court Remand Order Sheet", weight: 1.0, rank: "1st (Adjudicating)" },
        { source: "e-Prisons Register", weight: 0.95, rank: "2nd (Fact)" },
        { source: "Police FIR / CCTNS", weight: 0.85, rank: "3rd (Reference)" },
        { source: "OCR Perception Engine", weight: 0.75, rank: "4th (Probabilistic)" },
      ],
      columns: [
        {
          source_name: "e-Prisons Register",
          authority: "Yerwada Central Prison",
          recorded_value: "Continuous Custody: 950 Days",
          detention_days: 950,
          reliability_score: 0.95,
          status: "PRIMARY",
          notes: "Jail admission log verifies 950 continuous lockup days from 10-08-2023 without interruption.",
        },
        {
          source_name: "Court Remand Sheet",
          authority: "Sessions Court, Pune",
          recorded_value: "Qualifying Custody: 770 Days (-180 Days Delay)",
          detention_days: 770,
          reliability_score: 1.0,
          status: "CONTESTED",
          notes: "Prosecution claims 12 adjournments (180 days) attributable to defense. Contested by DLSA lawyer.",
        },
        {
          source_name: "Police FIR / CCTNS",
          authority: "Shivajinagar Police Station",
          recorded_value: "FIR Log: 950 Days Remand",
          detention_days: 950,
          reliability_score: 0.85,
          status: "CORROBORATING",
          notes: "Police CCTNS case history records single continuous remand without intermediate release.",
        },
      ],
      resolution_action: "CONFLICT FLAGGED → routed for Magistrate adjudication (Article 21)",
    },
  },
  "CASE-2088": {
    case: {
      id: "CASE-2088",
      prisoner_id: "P-2088",
      fir_number: "FIR 88/2023",
      court: "District Court, Lucknow",
      sections: ["IPC 420"],
      custody_start: "2023-08-02",
      maximum_sentence_years: 5,
      first_time_offender: true,
      multiple_pending_cases: false,
      punishable_by_death_or_life: false,
      next_hearing: "2026-08-21",
      documents: 8,
      is_uploaded: false,
    },
    prisoner: {
      id: "P-2088",
      name: "Meera Devi",
      prison_number: "UP-2088",
      age: 34,
      gender: "Female",
      prison_name: "District Jail, Lucknow",
      district: "Lucknow",
      state: "Uttar Pradesh",
      risk: "Low",
    },
    decision: {
      case_id: "CASE-2088",
      status: "ELIGIBLE",
      outcome: "ELIGIBLE_FOR_SECTION_479_RELEASE",
      eligible: true,
      detention_days: 748,
      qualifying_detention_days: 748,
      threshold_days: 608,
      days_remaining: 0,
      progress_percent: 123,
      excluded_delay_days: 0,
      rule_version: "2024.1",
      legal_basis: "Section 479(1) First Proviso BNSS",
      reasons: [
        "First-time female offender has served 748 days, surpassing the 1/3 statutory threshold of 608 days for 5-year maximum sentence.",
      ],
      exclusions: [],
      flags: [],
      trace: [
        { step: "Exclusion Check: Heinous Offence", result: "PASS", detail: "IPC 420 carries 5 years max sentence." },
        { step: "Classification: First-Time Offender", result: "APPLIED", detail: "1/3 threshold applicable." },
        { step: "Statutory Calculation", result: "ELIGIBLE", detail: "Served 748 days vs 608 days threshold." },
      ],
      requires_human_review: false,
      generated_at: "2026-08-19T10:00:00Z",
    },
    workflow: {
      case_id: "CASE-2088",
      levels: [
        { level: 1, role: "Legal Aid Defense Counsel", status: "APPROVED", actor: "Adv. R. Varma", note: "Verified", at: "2026-08-18T10:00:00Z" },
        { level: 2, role: "DLSA Secretary / Judicial Magistrate", status: "PENDING", actor: null, note: null, at: null },
      ],
      current_level: 2,
      final_decision: "PENDING",
      next_action: "Awaiting DLSA Secretary bond order issuance.",
    },
    document_lines: [
      "IN THE COURT OF CHIEF JUDICIAL MAGISTRATE, LUCKNOW",
      "CRIMINAL CASE NO: 88/2023 · OFFENCE: SECTION 420 IPC (CHEATING)",
      "STATE OF U.P.  --- VERSUS ---  MEERA DEVI",
      "REMAND COMMENCEMENT DATE: 02-08-2023",
      "MAXIMUM SENTENCE: 5 YEARS RIGOROUS IMPRISONMENT (1825 DAYS)",
      "FIRST-TIME OFFENDER: YES · 1/3 STATUTORY THRESHOLD = 608 DAYS",
      "TOTAL TIME SERVED IN DISTRICT JAIL LUCKNOW: 748 DAYS",
      "ELIGIBILITY: OVERDUE FOR STATUTORY BAIL BY 140 DAYS",
    ],
  },
  "CASE-4471": {
    case: {
      id: "CASE-4471",
      prisoner_id: "P-4471",
      fir_number: "FIR 304/2024",
      court: "Special Court, Ranchi",
      sections: ["IPC 323"],
      custody_start: "2024-03-01",
      maximum_sentence_years: 2,
      first_time_offender: true,
      multiple_pending_cases: false,
      punishable_by_death_or_life: false,
      next_hearing: "2026-09-04",
      documents: 5,
      is_uploaded: false,
    },
    prisoner: {
      id: "P-4471",
      name: "Sita Lakra",
      prison_number: "JH-4471",
      age: 26,
      gender: "Female",
      prison_name: "Birsa Munda Central Jail",
      district: "Ranchi",
      state: "Jharkhand",
      risk: "Low",
    },
    decision: {
      case_id: "CASE-4471",
      status: "APPROACHING",
      outcome: "APPROACHING_SECTION_479_THRESHOLD",
      eligible: false,
      detention_days: 215,
      qualifying_detention_days: 215,
      threshold_days: 243,
      days_remaining: 28,
      progress_percent: 88,
      excluded_delay_days: 0,
      rule_version: "2024.1",
      legal_basis: "Section 479(1) First Proviso BNSS",
      reasons: [
        "First-time offender has served 215 days of 243-day threshold (1/3 of 2 years). Reaches statutory eligibility in 28 days.",
      ],
      exclusions: [],
      flags: ["APPROACHING_THRESHOLD_MONITORING"],
      trace: [
        { step: "Exclusion Check: Heinous Offence", result: "PASS", detail: "IPC 323 carries 2 years max sentence." },
        { step: "Threshold Calculation", result: "MONITOR", detail: "215 days served / 243 days required (88%)." },
      ],
      requires_human_review: false,
      generated_at: "2026-08-19T10:00:00Z",
    },
    workflow: {
      case_id: "CASE-4471",
      levels: [
        { level: 1, role: "Legal Aid Defense Counsel", status: "PENDING", actor: null, note: null, at: null },
        { level: 2, role: "DLSA Secretary / Judicial Magistrate", status: "LOCKED", actor: null, note: null, at: null },
      ],
      current_level: 1,
      final_decision: "PENDING",
      next_action: "Queued for automatic notice to DLSA on threshold maturity date (2026-09-16).",
    },
    document_lines: [
      "IN THE SPECIAL COURT AT RANCHI, JHARKHAND",
      "SPECIAL CASE NO: 304/2024 · CHARGE: SECTION 323 IPC",
      "STATE OF JHARKHAND  --- VERSUS ---  SITA LAKRA",
      "CUSTODY START DATE: 01-03-2024 · MAX SENTENCE: 2 YEARS (730 DAYS)",
      "FIRST-TIME OFFENDER 1/3 THRESHOLD: 243 DAYS",
      "CURRENT TIME SERVED: 215 DAYS (88% OF THRESHOLD REACHED)",
      "DAYS TO MATURITY: 28 DAYS REMAINING UNTIL STATUTORY ELIGIBILITY",
    ],
  },
};

export const DEMO_PROOFS: Record<string, ProofCardPayload> = {
  "CASE-1042": {
    case_id: "CASE-1042",
    generated_at: "2026-08-19T10:00:00Z",
    status: "ELIGIBLE",
    outcome: "ELIGIBLE_FOR_SECTION_479_RELEASE",
    legal_basis: "Section 479(1) First Proviso BNSS",
    rule_version: "2024.1",
    flags: [],
    summary: [
      "First-time offender custody (412 days) exceeds 1/3 statutory threshold (365 days).",
      "Zero accused delay recorded across all court order sheets.",
    ],
    facts: {
      detention_days: 412,
      qualifying_detention_days: 412,
      excluded_delay_days: 0,
      threshold_days: 365,
      days_remaining: 0,
      progress_percent: 112,
    },
    perception_info: {
      ocr_provider: "EasyOCR Engine (PyTorch)",
      llm_provider: "Groq Llama-3-70B (Cloud / Fallback: Ollama Llama-3 Edge)",
      extraction_confidence: 0.98,
    },
    document_lines: [
      "IN THE COURT OF PRINCIPAL SESSIONS JUDGE, CHENNAI",
      "SESSIONS CASE NO: SC/412/2024 · ARISING FROM CRIME NO: 221/2024",
      "POLICE STATION: CRIME BRANCH (CENTRAL), CHENNAI DISTRICT",
      "STATE OF TAMIL NADU  --- VERSUS ---  AARAV KUMAR S/O R. KUMAR",
      "UNDER SECTIONS: 379 IPC (THEFT), 411 IPC (RECEIVING STOLEN PROPERTY)",
      "DATE OF INITIAL REMAND INTO JUDICIAL CUSTODY: 15-01-2024",
      "MAXIMUM PRESCRIBED STATUTORY SENTENCE: 3 YEARS RIGOROUS IMPRISONMENT",
      "CONVICTION RECORD CHECK: NO PRIOR CONVICTIONS ON ICJS (FIRST-TIME OFFENDER)",
      "MULTIPLE PROCEEDINGS: ZERO OTHER PENDING INVESTIGATIONS OR SESSIONS CASES",
      "ORDER OF ADJOURNMENTS: ALL PRE-TRIAL HEARINGS PROCEEDED UNDER COURT SCHEDULE",
      "ACCUSED-ATTRIBUTABLE DELAYS RECORDED: NIL (0 DAYS DEDUCTION)",
      "TOTAL CONTINUOUS CUSTODY SERVED (AS OF 19-08-2026): 412 DAYS",
      "STATUTORY APPLICABILITY: SECTION 479(1) FIRST PROVISO BNSS (1/3 THRESHOLD = 365 DAYS)",
      "DISPOSITION RECOMMENDATION: ELIGIBLE FOR MANDATORY BAIL REVIEW UNDER BNSS S.479",
    ],
    sources: [
      {
        field: "custody_start",
        label: "Court Remand Order",
        value: "2024-01-15 (Remand Sheet p.1)",
        confidence: 0.98,
        selected: true,
        requires_human_review: false,
        source_line: 5,
      },
      {
        field: "sections",
        label: "Charges in Police FIR 221/2024",
        value: "IPC 379 / 411 (Max 3 Years)",
        confidence: 0.96,
        selected: true,
        requires_human_review: false,
        source_line: 4,
      },
      {
        field: "first_time_offender",
        label: "e-Prisons Admission Register",
        value: "No prior criminal convict record",
        confidence: 0.96,
        selected: true,
        requires_human_review: false,
        source_line: 7,
      },
      {
        field: "accused_delay",
        label: "Order Sheet Chronology",
        value: "0 days defense delay (Nil)",
        confidence: 0.92,
        selected: true,
        requires_human_review: false,
        source_line: 10,
      },
      {
        field: "detention_days",
        label: "Continuous Custody Count",
        value: "412 continuous days served",
        confidence: 0.99,
        selected: true,
        requires_human_review: false,
        source_line: 11,
      },
    ],
    disclaimer:
      "Decision support only. A designated legal officer must verify source documents before action.",
  },
  "CASE-5099": {
    case_id: "CASE-5099",
    generated_at: "2026-08-19T10:00:00Z",
    status: "INELIGIBLE",
    outcome: "STATUTORY_EXCLUSION_LIFE_DEATH",
    legal_basis: "Section 479(1) Exclusion Bar BNSS",
    rule_version: "2024.1",
    flags: ["STATUTORY_DISQUALIFICATION_TRIGGERED"],
    summary: [
      "Disqualified under Section 479(1) BNSS: Charged under IPC Section 302.",
      "Multiple pending sessions trials recorded in CCTNS.",
    ],
    facts: {
      detention_days: 640,
      qualifying_detention_days: 640,
      excluded_delay_days: 0,
      threshold_days: null,
      days_remaining: null,
      progress_percent: 0,
    },
    perception_info: {
      ocr_provider: "EasyOCR Engine (PyTorch)",
      llm_provider: "Groq Llama-3-70B (Cloud / Fallback: Ollama Llama-3 Edge)",
      extraction_confidence: 0.99,
    },
    document_lines: [
      "IN THE SESSIONS COURT AT KOLKATA, WEST BENGAL",
      "SESSIONS TRIAL CASE NO: ST/71/2022 · ARRESTING PS: TALTALA",
      "STATE OF WEST BENGAL  --- VERSUS ---  ROHIT DAS S/O LATE B. DAS",
      "CHARGES FRAMED UNDER: SECTION 302 IPC (MURDER) READ WITH SECTION 34 IPC",
      "STATUTORY PENALTY: PUNISHABLE WITH DEATH OR IMPRISONMENT FOR LIFE",
      "INTER-STATE CRIMINAL RECORD: 2 OTHER SESSIONS TRIALS PENDING IN ALIPORE COURT",
      "DATE OF COMMENCEMENT OF DETENTION: 22-11-2022",
      "TOTAL CUSTODY SERVED TO DATE: 640 DAYS IN PRESIDENCY CORRECTIONAL HOME",
      "STATUTORY EXCLUSION ANALYSIS UNDER SECTION 479(1) BNSS:",
      "1. CAPITAL / LIFE IMPRISONMENT CLAUSE: EXCLUDED UNDER SECTION 479(1)",
      "2. MULTIPLE PENDING PROCEEDINGS CLAUSE: EXCLUDED UNDER SECTION 479(2)",
      "FINAL DETERMINATION: ZERO-BAIL MANDATORY DISQUALIFICATION APPLIED",
    ],
    sources: [
      {
        field: "sections",
        label: "Charge Sheet (Sessions Court Kolkata)",
        value: "IPC Section 302 (Murder), Section 34",
        confidence: 0.99,
        selected: true,
        requires_human_review: false,
        source_line: 3,
      },
      {
        field: "penalty",
        label: "Statutory Penalty Classification",
        value: "Punishable with Death or Life Imprisonment",
        confidence: 0.99,
        selected: true,
        requires_human_review: false,
        source_line: 4,
      },
      {
        field: "multiple_cases",
        label: "CCTNS Inter-State Portal",
        value: "2 pending sessions cases in WB/Kolkata",
        confidence: 0.95,
        selected: true,
        requires_human_review: false,
        source_line: 5,
      },
      {
        field: "custody_start",
        label: "Presidency Jail Admission Log",
        value: "22-11-2022 (640 days served)",
        confidence: 0.98,
        selected: true,
        requires_human_review: false,
        source_line: 6,
      },
    ],
    disclaimer:
      "Decision support only. A designated legal officer must verify source documents before action.",
  },
  "CASE-3156": {
    case_id: "CASE-3156",
    generated_at: "2026-08-19T10:00:00Z",
    status: "ELIGIBLE_FLAGGED",
    outcome: "DISPUTED_ACCUSED_DELAY_REQUIRES_MAGISTRATE_REVIEW",
    legal_basis: "Section 479(1) BNSS & Article 21 Safeguard",
    rule_version: "2024.1",
    flags: ["ACCUSED_DELAY_DISPUTE", "ARTICLE_21_HEARING_REQUIRED"],
    summary: [
      "180 days delay attributed to defense by prosecution is disputed by DLSA legal counsel.",
      "Requires judicial verification under Section 479(2) BNSS.",
    ],
    facts: {
      detention_days: 950,
      qualifying_detention_days: 770,
      excluded_delay_days: 180,
      threshold_days: 1825,
      days_remaining: 1055,
      progress_percent: 42,
    },
    perception_info: {
      ocr_provider: "EasyOCR Engine (PyTorch)",
      llm_provider: "Groq Llama-3-70B (Cloud / Fallback: Ollama Llama-3 Edge)",
      extraction_confidence: 0.88,
    },
    document_lines: [
      "IN THE COURT OF SESSIONS JUDGE AT PUNE, MAHARASHTRA",
      "SESSIONS CASE NO: 19/2025 · POLICE STATION: SHIVAJINAGAR",
      "STATE OF MAHARASHTRA  --- VERSUS ---  IMRAN KHAN",
      "CHARGES UNDER: SECTION 307 IPC (ATTEMPT TO MURDER) · MAX SENTENCE: 10 YEARS",
      "DATE OF PRISON ADMISSION (YERWADA PRISON): 10-08-2023 (950 DAYS IN CUSTODY)",
      "PROSECUTION MEMO: CLAIMS 180 DAYS DEFENSE ADJOURNMENT DELAY UNDER S.479(2)",
      "DLSA DEFENSE OBJECTION: 180 DAYS CAUSED BY PROSECUTION WITNESS ABSENCE",
      "QUALIFYING DETENTION COMPUTATION: 950 DAYS RAW - 180 DAYS CONTESTED = 770 DAYS",
      "STATUTORY THRESHOLD: 1/2 OF 10 YEARS = 5 YEARS (1825 DAYS)",
      "SOURCE CONFLICT DETECTED: PRISON REGISTER (950 DAYS) VS PROSECUTION DEDUCTION (770 DAYS)",
      "ARTICLE 21 STATUTORY SAFEGUARD: DEDUCTION CONTESTED; ESCALATED FOR MAGISTRATE HEARING",
    ],
    sources: [
      {
        field: "custody_start",
        label: "Yerwada Jail Admission Register",
        value: "2023-08-10 (Total: 950 days in custody)",
        confidence: 0.98,
        selected: true,
        requires_human_review: false,
        source_line: 4,
      },
      {
        field: "sections",
        label: "Court Charges",
        value: "IPC 307 (Attempt to Murder · 10 Yr Max)",
        confidence: 0.95,
        selected: true,
        requires_human_review: false,
        source_line: 3,
      },
      {
        field: "accused_delay",
        label: "Prosecution Adjournment Log",
        value: "180 days defense absence (Contested by DLSA)",
        confidence: 0.76,
        selected: true,
        requires_human_review: true,
        source_line: 5,
      },
      {
        field: "defense_plea",
        label: "Legal Aid Counsel Objection",
        value: "Delay caused by Prosecution Witness Non-Appearance",
        confidence: 0.89,
        selected: true,
        requires_human_review: true,
        source_line: 6,
      },
      {
        field: "qualifying_days",
        label: "Qualifying Custody Math",
        value: "770 days calculated (1055 days to 1825 threshold)",
        confidence: 0.94,
        selected: true,
        requires_human_review: false,
        source_line: 7,
      },
    ],
    disclaimer:
      "Decision support only. A designated legal officer must verify source documents before action.",
  },
};
